language: node_js
node_js:
  - "7"
# branches:
#   only:
#     - master
#     - dev
cache:
  directories:
    - node_modules
install: npm install
jobs:
  include:
    - stage: test
      script: npm run jest
    - stage: deploy
      script: npm run build:demo
# script: npm run jest
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    # keep-history: true
    # local-dir: dist
    # target-branch: gh-pages #推送local-dir 内容到，默认为gh-pages
