language: node_js
node_js: stable
cache:
  directories:
  - node_modules
install: npm install
notifications:
  email:
    recipients:
      - zhouqing2@aiyoumi.com
    on_success: always # default: change
    on_failure: always # default: always
jobs:
  include:
  - stage: deploy
    # script: npm run build & npm run build:demo
    script: npm run build:modules
    deploy:
    # - provider: pages
    #   skip-cleanup: true
    #   local-dir: dist
    #   github-token: "$git_token"
    #   on:
    #     branch: dev
    #     repo: Aiyoumi-FE/aym-ui
    #     # tags: true
    - provider: script
      skip-cleanup: true
      api_key:
        secure: JzAl9PPzU/igygtpftCjHYmm/UuQHYW4rII5HMH6l+HVML5gob/jClYMiR1Of6jPbFUmUF1CtSb0x8ABoFq7Pg919Jjx5vO2uI4N32Ilnn1pEKSyFtxaJ8zpNba9wbn5pF35TsZT0NBkGccBrJG3HjYvMbCeuqIsvthqdK+wLeXIaNouF1YP+nTmQBrvwI63nxidw5ojO5W233SqQcMIuiNRoQYexj91aXGBeJovGKq7Neswe+MUdcheUNjK3D6ETCd3oindVPSScJlz3Z9yxhwWojeGkKwIGWX/dGod2LkZs0DIHCwDm69bGFXgUSDPPTzw0hzxIRhO1aW69TJIkZBDYt/AFdR+Nz2Fpl1HEdjuWiAxf9rpPrcYcdEQ4BD+WXpFE8Nr/ltYliBLHi/mOsbeTTMLRt+hTyS7+JxWxDAidCZc68msa+QhK/jbv7nm/9s2KtepHCMCZ00RSLEZ8pj/fDuFWpAz4ikL24VxMSe7r6OFEbMH975ZbgFUvYX33FPchlX1JjP9UXy7TovDDcPFHFozuPArc1raxDSAaXdtyLgjiQAvpOBNC/5WG6HvfhE2q4SaEm77AEMJOV4B2s/YbzpQqdiTPSAEaujhCMjPUBpuYbmJj7bqIx6Xls/FnSLfCkx+HGfGkcvQi6vv6MKJ7UErVSp2AVZxcvl1jHM=
      script: npm run release
      on:
        branch: dev
        repo: Aiyoumi-FE/aym-ui
        # tags: true
    # - provider: releases
    #   script: npm run release
    #   api_key:
    #     secure: JzAl9PPzU/igygtpftCjHYmm/UuQHYW4rII5HMH6l+HVML5gob/jClYMiR1Of6jPbFUmUF1CtSb0x8ABoFq7Pg919Jjx5vO2uI4N32Ilnn1pEKSyFtxaJ8zpNba9wbn5pF35TsZT0NBkGccBrJG3HjYvMbCeuqIsvthqdK+wLeXIaNouF1YP+nTmQBrvwI63nxidw5ojO5W233SqQcMIuiNRoQYexj91aXGBeJovGKq7Neswe+MUdcheUNjK3D6ETCd3oindVPSScJlz3Z9yxhwWojeGkKwIGWX/dGod2LkZs0DIHCwDm69bGFXgUSDPPTzw0hzxIRhO1aW69TJIkZBDYt/AFdR+Nz2Fpl1HEdjuWiAxf9rpPrcYcdEQ4BD+WXpFE8Nr/ltYliBLHi/mOsbeTTMLRt+hTyS7+JxWxDAidCZc68msa+QhK/jbv7nm/9s2KtepHCMCZ00RSLEZ8pj/fDuFWpAz4ikL24VxMSe7r6OFEbMH975ZbgFUvYX33FPchlX1JjP9UXy7TovDDcPFHFozuPArc1raxDSAaXdtyLgjiQAvpOBNC/5WG6HvfhE2q4SaEm77AEMJOV4B2s/YbzpQqdiTPSAEaujhCMjPUBpuYbmJj7bqIx6Xls/FnSLfCkx+HGfGkcvQi6vv6MKJ7UErVSp2AVZxcvl1jHM=
    #   skip-cleanup: true
    #   file_glob: true
    #   file: lib/**/*
    #   on:
    #     branch: dev
    #     repo: Aiyoumi-FE/aym-ui
    #     # tags: true

