language: node_js
node_js: stable
cache:
  directories:
  - node_modules
install: npm install
notifications:
  email:
    recipients:
      - zhouqing2@aiyoumi.com
    on_success: always # default: change
    on_failure: always # default: always
branches:
  only:
    - master
    - dev
jobs:
  include:
  - stage: test
    script: npm run jest
  # - stage: deploy
  #   script: npm run build
  #   deploy:
  #   - provider: pages
  #     skip-cleanup: true
  #     local-dir: dist
  #     github-token: "$git_token"
  #     on:
  #       branch: dev
  #       repo: Aiyoumi-FE/aym-ui
after_success:
  - "curl -o /tmp/travis-automerge https://raw.githubusercontent.com/zq741235/travis-automerge/master/travis-automerge"
  - "chmod a+x /tmp/travis-automerge"
  - "BRANCHES_TO_MERGE_REGEX='^dev$' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=Aiyoumi-FE/aym-ui /tmp/travis-automerge"
